import type {V2Timeline} from './types';
import {FUTURE_COMMAND} from './copy';

export const websiteV2: V2Timeline = {
  frames: 2550,
  layout: 'landscape',
  scenes: [
    {
      id: 'command',
      from: 0,
      duration: 150,
      kind: 'command',
      headline: FUTURE_COMMAND,
      voice: '未来，经营店群，也许只需要一句话。',
    },
    {
      id: 'organization-boot',
      from: 150,
      duration: 270,
      kind: 'organization',
      headline: '目标进入，AI 组织开始运转',
      voice: '目标进入 AXIO，治理、计划、建议与执行逐级启动。',
    },
    {
      id: 'positioning',
      from: 420,
      duration: 180,
      kind: 'statement',
      headline: '不是一个 AI 工具',
      voice: '这不是一个 AI 工具。这是一套 AI 电商经营组织。',
    },
    {
      id: 'proof',
      from: 600,
      duration: 240,
      kind: 'proof',
      headline: '116 家店 · 6 个站点 · 2 个租户',
      voice: '一百一十六家店，六个站点，两个独立租户。AXIO，诞生于真实经营。',
      evidence: 'matrix-pricing.webp',
    },
    {
      id: 'plan',
      from: 840,
      duration: 600,
      kind: 'evidence',
      headline: '经营目标，变成可验收计划',
      voice: '你定义目标。AI Supervisor 拆解选品、站点、数量、利润、证据和验收标准。成本、汇率、平台费、物流与目标利润，每一项透明可查。',
      evidence: 'task-pricing.webp',
    },
    {
      id: 'governance',
      from: 1440,
      duration: 420,
      kind: 'governance',
      headline: '效率与治理，双轨制衡',
      voice: 'AI Supervisor 是唯一正式任务派发者。ACCIO 监督方向、权限、风险与纠偏。专业 Agent 只提交建议。最终决策权，始终在创始人手里。',
      evidence: 'risk-control.webp',
    },
    {
      id: 'readback',
      from: 1860,
      duration: 300,
      kind: 'loop',
      headline: '脚本完成，不等于业务成功',
      voice: '获批任务交给确定性脚本与妙手执行。状态、异常、订单和利润必须回读、分类和复盘。',
      evidence: 'supervisor.webp',
    },
    {
      id: 'vision',
      from: 2160,
      duration: 240,
      kind: 'vision',
      headline: '受控执行 → 7×24 高级运营',
      voice: '今天，它在受控执行中进化。下一步，是可监督、可纠偏、可随时停止的七乘二十四小时运营。',
    },
    {
      id: 'brand',
      from: 2400,
      duration: 150,
      kind: 'brand',
      headline: '然后，整个 AI 组织开始工作。',
      voice: '这个月，帮我赚十万。然后，整个 AI 组织开始工作。AXIO 智核。',
    },
  ],
};

export const wechatV2: V2Timeline = {
  frames: 1500,
  layout: 'portrait-independent',
  scenes: [
    {
      id: 'organization',
      from: 0,
      duration: 240,
      kind: 'organization',
      headline: '一套 AI 电商经营组织',
      voice: '这不是一个 AI 工具。这是一套 AI 电商经营组织。',
    },
    {
      id: 'proof',
      from: 240,
      duration: 180,
      kind: 'proof',
      headline: '116 家店 · 6 个站点',
      voice: '一百一十六家店，六个站点。AXIO，诞生于真实经营。',
      evidence: 'matrix-pricing.webp',
    },
    {
      id: 'operating',
      from: 420,
      duration: 480,
      kind: 'evidence',
      headline: '一句目标，拆成经营计划',
      voice: '你说目标，AI Supervisor 拆计划、证据和验收。透明定价，风险检查，获批后再交给妙手执行。',
      evidence: 'task-pricing.webp',
    },
    {
      id: 'governance',
      from: 900,
      duration: 300,
      kind: 'governance',
      headline: 'ACCIO 纠偏 · AI Supervisor 派发',
      voice: 'ACCIO 监督方向与风险。AI Supervisor 保持唯一正式派发权。自动化，不是黑盒。',
      evidence: 'risk-control.webp',
    },
    {
      id: 'trial',
      from: 1200,
      duration: 300,
      kind: 'trial',
      headline: '前 50 位 · 免费试用 7 天',
      voice: '新品上线，招募前五十位粉丝免费试用七天。最多三家店，先从计划模式开始。',
    },
  ],
};
